# RESTful-API-test task-readme-github-pages.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: RESTful-API-test

outputs:
- name: RESTful-API-test-updated

run:
  path: ./RESTful-API-test/ci/scripts/readme-github-pages.sh
  # args: [-debug]
