platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: RESTful-API-test

outputs:
- name: coverage-results

run:
  path: ./RESTful-API-test/ci/scripts/unit-tests.sh
    # args: [-debug]
